### ISSUE TITLE
Directories not visible in File Explorer

### ISSUE THREAD

**Issue by matthewp** [jordwalke/flatlandia#1]
![screen shot 2014-03-10 at 2 01 22 pm](https://f.cloud.github.com/assets/361671/2377054/035ab482-a87e-11e3-8ba4-fa51a541ee0a.png)

**Comment by jordwalke** [comment]
This looks like terminal, correct? Not MacVim? (Is it iTerm or mac's built in terminal)?

**Comment by matthewp** [comment]
Yes, it's iTerm, should I only use it within MacVim?

**Comment by jordwalke** [comment]
I only intended support for MacVim, but we can pretty easily fix up terminal support so may as well do it. Just need to copy over any of the existing colors from the upstream flatland repo: https://github.com/thinkpixellab/flatland
I'll take a look in about 10 minutes or you can give it a shot in the mean time.

**Comment by jordwalke** [comment]
I'll fix the NERD coloring, which makes the text editing much better, but vim-airline will still quite horrible on a terminal (I'll update the README and file an issue - feel free to fix `flatlandia.vim` inside of `autoload/`) . The trouble is that in Vim, you must explicitly choose the fallback terminal colors. There are colorscheme frameworks for Vim that choose the closest one for you, but they don't work on terminal. Someone should invent a plugin that rehighlights everything in terminal mode so you only have to worry about specifying hex colors.
