### ISSUE TITLE
Remove hi clear

### ISSUE THREAD

**Issue by fingermark** [jordwalke/flatlandia#5]
Can we either remove `hi clear` or make it a configurable, because I have a lot of custom color definitions in my vimrc file and various plugins.  Calling colo flatlandia seems to reset those.

**Comment by fingermark** [comment]
I guess solarized uses hi clear too.  I guess we can ignore this.

**Comment by jordwalke** [comment]
If you have custom highlighting, shouldn't you put some hook in place to listen to when colorschemes change so you can reapply them? I'm honestly not sure what the right solution is.
